### ISSUE TITLE
Lua to Redis decimal numbers changed

### ISSUE THREAD

**Issue by bybera** [tporadowski/redis#16]
Hi, I am using redis 3.2.100 version on windows. The same problem exist in the 4.0.2 (alpha) version.
The values is changing when converting string to number with a lua script.  I would like your help.
I share the problem I'm experiencing below.

![2](https://user-images.githubusercontent.com/38812660/39401657-2969c920-4b53-11e8-988a-648adc1261f3.png)

**Comment by tporadowski** [comment]
It seems like an issue of getting back the result value to Redis - as ```tostring(tonumber(incomingVal))``` inside a Lua script leaves the value still as "0.005". I saw you found antirez/redis#1118 - I will have a look how this is related.

**Comment by tporadowski** [comment]
This issue is also reproducible on Linux version of Redis, but in general - it is related to [double-precision floating-point format](https://en.wikipedia.org/wiki/Double-precision_floating-point_format), which cannot precisely represent some numbers in the way we work with them (```0.005``` is one of them). You can have a look [at this example](https://codepad.remoteinterview.io/JPJSCJIZPK) I wrote on some "codepad" online service. When result of ```tonumber()``` is passed back to Lua's engine it uses [strtod](http://www.cplusplus.com/reference/cstdlib/strtod/) function, which makes string ```0.005``` to appear as ```0.0050000000000000001``` when full 17 digits of precision are considered.
Some further reading:
  * http://krashan.ppa.pl/articles/stringtofloat/
  * https://github.com/grzegorz-kraszewski/stringtofloat (implementation of above, gave the same result)
  * http://www.exploringbinary.com/how-strtod-works-and-sometimes-doesnt/

@ultranett - I guess you'll either have to live with that or use something else than ```double``` type.
