### ISSUE TITLE
通过java程序无法读取命令响应结果--scan/--bigkeys/--stat

### ISSUE THREAD

**Issue by redisviewer** [tporadowski/redis#39]
redis-cli -h 10.221.164.116 -p 7004 --bigkeys
![image](https://user-images.githubusercontent.com/12822830/64591900-73782e80-d3dd-11e9-8183-1932bc14acb9.png)
![image](https://user-images.githubusercontent.com/12822830/64591906-77a44c00-d3dd-11e9-9d7a-a21ba4e3bef0.png)
控制台可以返回消息，但使用java调用cmd则无法拿到返回值，类似的命令还有--stat --scan

以下是正常的 dbsize、get key、ttl key、cluster info、cluster nodes、info等等...

**Comment by tporadowski** [comment]
@travishao if you could post your question in English you may get some more help. What is the point of running `redis-cli` via either `bash` or `cmd`?

**Comment by redisviewer** [comment]
> @travishao if you could post your question in English you may get some more help. What is the point of running `redis-cli` via either `bash` or `cmd`?

![image](https://user-images.githubusercontent.com/12822830/64607399-06739180-d3fb-11e9-8595-ca64f4852e37.png)

I tried to develop my own GUI client tools. It has a console feature and I hope it is a powerful console that mimics the redis-cli console as much as possible.
The existing Java redis-lib did not directly call the command of redis-cli.
So use redis-cli(.exe) boldly in redis release package as my communication tool with java, 
most of the commands work fine, except --bigkeys/ --scan/ --stat...

**Comment by tporadowski** [comment]
What is your use case here exactly? Do you need to parse the output of `redis-cli` or you just want it to send the commands to given Redis instance? What doesn't work for those commands you listed at the end?

**Comment by redisviewer** [comment]
I need to parse the output of redis-cli with command "--bigkeys", then return null

**Comment by tporadowski** [comment]
There is nothing special about output from `--bigkeys` - it does the search, outputs results and calls `exit(0)`. Perhaps you can just try reading `redis-cli.exe` output directly rather than through `cmd` wrapper and debug what happens if something does not work in that part of your application?

Since this is not really a bug report related to Redis - I will close this issue. I do encourage you however to move this to [StackOverflow](https://stackoverflow.com/)
