### ISSUE TITLE
New version release date

### ISSUE THREAD

**Issue by shijuabraham** [tporadowski/redis#40]
Thanks for all the hard work you guys put in for this. Do you know what the approximate date would be for the next version (with module support)?

**Comment by tporadowski** [comment]
Hi Shiju,
I am sorry I missed your email, so will reply here. I would like to upgrade code base to latest 4.0.14 and then release it (especially when unit tests are passing on my new laptop), but due to lack of time I have no estimate for that. Please keep in mind that modules support for Windows version of Redis will require major (or maybe just minor) adjustments to their source code, as they were mostly written for Linux version. Are you interested in any particular module or maybe have your own that could be tested with current implementation? If you need this latest version with modules support for development or testing, but cannot provide that module to me - then I can compile the project and make it available for you for download.

**Comment by shijuabraham** [comment]
Hi Tomasz,
The only module I was interested in was Rejson and RediSearch
Thanks
Shiju

**Comment by tporadowski** [comment]
It seems that thanks to @israellot we're heading towards 4.0.14 release soon, so stay tuned. As I mentioned in regard to ReJSON - you can already have a look at [my ReJSON fork for Windows](https://github.com/tporadowski/rejson) and especially [this commit](https://github.com/tporadowski/rejson/commit/a19d4ad009312fce2c2b38cd388defe7c824d190) to see what changes were needed to get that module running under Redis for Windows. AS for RediSearch - you will have to determine it yourself.

**Comment by tporadowski** [comment]
There is also a short [Wiki page about modules](https://github.com/tporadowski/redis/wiki/Redis-modules)

**Comment by tporadowski** [comment]
I have just resolved the last obstacle that prevented unit tests from completing successfully (at least on my machine), so it seems we have 4.0.14 stable on _develop_ branch. I should release it then today or tomorrow.

**Comment by tporadowski** [comment]
[Redis 4.0.14 for Windows](https://github.com/tporadowski/redis/releases/tag/v4.0.14) is now released.

**Comment by shijuabraham** [comment]
Thanks a lot guys for all this awesome work.
