### ISSUE TITLE
Enable loading of modules

### ISSUE THREAD

**Issue by tporadowski** [tporadowski/redis#6]
At the moment modules are turned off as their initialization was causing some problems. Goal of this task:
- Enable loading of modules (though they'd have to be ported to Windows, too)
- mention usage of [dlfcn-win32 project](https://github.com/dlfcn-win32/dlfcn-win32); convert it to a separate library in deps? Make it a Git submodule?

**Comment by fpdavis** [comment]
My master node appears to be up and running fine, however, the slave node is giving the following error. I am assuming this is because of a module dependency issue? Any idea which module this would be and if it had previously been ported?

> [3980] 04 Dec 15:11:02.925 * Connecting to MASTER 192.168.0.XXX:6379
> [3980] 04 Dec 15:11:02.926 * MASTER <-> SLAVE sync started
> [3980] 04 Dec 15:11:03.930 * Non blocking connect for SYNC fired the event.
> [3980] 04 Dec 15:11:03.931 # Sending command to master in replication handshake: -Writing to master: The specified module could not be found.

**Comment by tporadowski** [comment]
@fpdavis: This problem is not related to modules and returned message is a bit misleading. "_The specified module could not be found_" is apparently error `ERROR_MOD_NOT_FOUND` returned by `write()` call when sending commands to master. Is it always reproducible for you?

**Comment by fpdavis** [comment]
Yes, the error message appears in the log every second. I have created a second install to do further testing with and am getting the same results. There is no indication in the master log file that a connection was even attempted. This could just be a setup issue on my end so I will double check the configuration file and try some different settings.

**Comment by tporadowski** [comment]
I tested replication to 2 slaves running on the same machine (just different ports). Yet, all instances were using out-of-the-box configuration, so I'd be interested to get to know yours to try to reproduce it.

**Comment by fpdavis** [comment]
@tporadowski thank you for you help. After a bit of troubleshooting **I have it working once again**! I did as you and had two fresh instances working without issue on my local machine but I still couldn't get it working in our test environment even after fresh installs. It turned out that I had two issues in my config files. 

The first issue was that I was binding only to 127.0.0.1 on the master (and slave) server so the slave couldn't connect to it. I tried commenting the "bind 127.0.0.1" line out (so it would bind to all interfaces) but then the process wouldn't start. I ended up putting in the actual IP address I needed the service to bind to. Running this on my local machine didn't uncover this issue.

The second issue I had (while testing on localhost) was that for the slaveof line in the configuration I put in "localhost" rather than "127.0.0.1" this caused the same or similar error as above.

Thank you for your time, sorry to clutter up this issue with something unrelated and entirely my fault.

**Comment by tporadowski** [comment]
Small update: I've started to work on this topic, current result is not ready to be committed, but at least I managed to get it working a bit:
![image](https://user-images.githubusercontent.com/6212622/44592394-b0688780-a7c0-11e8-9caf-8ff8f48d132d.png)

Is anyone interested in/willing/planning to migrate any Redis modules to Windows?

**Comment by tporadowski** [comment]
Changes related to enabling modules support are in branch "module-support": https://github.com/tporadowski/redis/tree/module-support

**Comment by tporadowski** [comment]
Modules support added in ea4c69747. Some mini guide on how to build/recompile modules might be needed + changes to [RedisModulesSDK](https://github.com/RedisLabs/RedisModulesSDK).
