### ISSUE TITLE
Are modules supported?

### ISSUE THREAD

**Issue by AachoLoya** [tporadowski/redis#84]
Are Redis modules supported in 4.0.14 and 5.0.9 releases? If so, any specific instructions for building modules or should I just create a simple windows dll and follow standard redis module development guidelines?

**Comment by tporadowski** [comment]
Yes, modules are supported. I once quickly ported ReJSON (now [RedisJSON](https://github.com/RedisJSON/RedisJSON)) for 4.0.2 for testing purposes - you can find it here: https://github.com/tporadowski/rejson. If you are looking for any existing modules - they have to be ported to Windows, otherwise you should follow mentioned guidelines when creating a new module and create a regular DLL to be loaded.

**Comment by AachoLoya** [comment]
Great! I've seen some memory access violation bugs being reported in 5.0.9. Is 4.0.14.2 version reliable for business use?

**Comment by tporadowski** [comment]
Yes, I consider v4.0.x to be more stable than current 5.0.9 release, which indeed has mostly problems with persisting data to RDB - I am trying to find the root cause of it.

**Comment by AachoLoya** [comment]
Is 4.0.x more stable than the old MSOpenTech releases?

**Comment by tporadowski** [comment]
Personally I only used older releases for a short time, so I cannot compare this aspect. I can only tell from the feedback I received and the number of reported issues that it is "stable enough" in my opinion. Plus it is still supported (at least until I release 6.x), unlike the archived version from MSOpenTech.
