### ISSUE TITLE
No support for TS CREATE function of redis timeseries

### ISSUE THREAD

**Issue by arul67800** [tporadowski/redis#90]
On adding time series data by using redis timeseries module produce error in python

rts.create('source', retention_msecs=40)

Traceback (most recent call last):

  File "<ipython-input-29-0d98d59077cf>", line 1, in <module>
    rts.create('source', retention_msecs=40)

  File "C:\ProgramData\Anaconda3\lib\site-packages\redistimeseries\client.py", line 214, in create
    return self.redis.execute_command(self.CREATE_CMD, *params)

  File "C:\ProgramData\Anaconda3\lib\site-packages\redis\client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)

  File "C:\ProgramData\Anaconda3\lib\site-packages\redis\client.py", line 915, in parse_response
    response = connection.read_response()

  File "C:\ProgramData\Anaconda3\lib\site-packages\redis\connection.py", line 756, in read_response
    raise response

ResponseError: unknown command `TS.CREATE`, with args beginning with: `source`, `RETENTION`, `40`, 

On adding time series data by using redis timeseries module produce error in python

**Comment by tporadowski** [comment]
`TS.CREATE` comes from an external module and is not by default available in Redis. Unfortunately, since this is a Windows port of Redis - modules need to be ported as well (on Linux they are loaded from shared libraries `*.so` and on Windows from `*.dll`). For the moment I am not aware of any modules publicly available for Redis for Windows port. When I was porting modules support for Redis 4.0.2 I also ported "ReJSON" (now [RedisJSON](https://github.com/RedisJSON/RedisJSON)) for handling JSON documents, but I have not tested it enough back then and not released it in binary form (sources are still available [here](https://github.com/tporadowski/rejson) for mentioned 4.0.x version).

**Comment by arul67800** [comment]
Any way thanks for the brilliant work..hope some progress for Time series module for redis in windows port in your consideration
